/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/Asteroid.glb 
*/

import React, { useRef } from 'react'
import { Sparkles, useGLTF } from '@react-three/drei'

export const SingleAsteroid1 = (props) => {
  const { nodes, materials } = useGLTF('/Asteroid1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Asteroid_Icosphere.geometry} material={materials.Asteroid} />
      <Sparkles count={50} scale={2} size={6} speed={0.4} />
    </group>
  )
}

useGLTF.preload('/Asteroid.glb')
