/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 public/Asteroid2.glb 
*/

import React, { useRef, useState } from 'react'
import { Sparkles, useCursor, useGLTF } from '@react-three/drei'

export const SingleAsteroid2 = (props) => {
  const { nodes, materials } = useGLTF('/Asteroid2.glb')

  const [hovered, hover] = useState(false)

  useCursor(hovered)

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials.Asteroid}
        onPointerOver={() => hover(true)}
        onPointerOut={() => hover(false)}
        scale={hovered ? 1.2 : 1}
      />
      <Sparkles count={25} scale={0.5} size={20} speed={0.5} />
    </group>
  )
}

useGLTF.preload('/Asteroid2.glb')
